### ISSUE TITLE
Search in content

### ISSUE THREAD

**Issue by rose-line** [Futureglobe/SnipAway_IssueTracker#14]
**Is your feature request related to a problem?**
Search filtering is based on snippets titles only. Sometimes I would like to view snippets that contain certain keywords *in the content*, such as the name of a function. The idea is to quickly spot a snippet for which I can't recall the name of, or to explore all snippets where this particular piece of code is used, within different contexts.

**Describe the solution you'd like**
An option to enable "Search within content". An option "Search within description" might be useful too. I suppose a quick access to these using checkbox-like buttons in the search bar could be the way to go.

**Comment by Futureglobe** [comment]
Hey @rose-line ,

Thank you for your feature request.

We think this idea is very good and we will add it on our Todo List.
Once this feature has been implemented by our team, we will make it available with an update.
We will inform you about it as soon as the feature exists.

Thank you for the very cool idea.

Your Futureglobe Support Team

**Comment by Futureglobe** [comment]
Hi @rose-line ,

we just wanted to let you know that we have implemented the feature you requested. 
It will be available with the next software update. We apologize for the long waiting time. But due to the current pandemic we had to put some features on hold.

Have a great week.

Your Futureglobe Support Team
