### ISSUE TITLE
Singleton instance

### ISSUE THREAD

**Issue by rose-line** [Futureglobe/SnipAway_IssueTracker#15]
**Is your feature request related to a problem?**
Don't know if it should be considered a problem, but I don't see the point of allowing multiple instances of the application. When "Leave Open in Background" is enabled, SnipAway is minimized in the tray, and using a shortcut to reload it (instead of the tray icon) actually loads a new instance. I found 8 instances of the app running in the tray when I first realized the problem ;) And I keep doing it by accident. 

**Describe the solution you'd like**
Launching the application when it is already running should pop the existing instance up instead of loading a new instance. Or, if there is actually a workflow that would benefit from multiple instances, consider adding a setting to enable/disable the behavior.

**Describe alternatives you've considered**
Using the tray icon (that could be hidden), or the global shortcuts provided by the app. This doesn't prevent me from clicking th App icon or using my App Launcher, which is my usual workflow.

**Comment by Futureglobe** [comment]
Hey @rose-line ,

Thank you for your comment on this behavior of our app.
A question directly in advance, on which platform do you use SnipAway?
We noticed that this behavior occurs more often on macOS systems.

Basically we find the idea of multiple instances of the app optimal to be able to use the app in multiple places at the same time. According to our statistics more than 25% of the users use the app with several instances at the same time. For users who don't want to have this functionality, we offer the possibility to deactivate the tray behaviour in the settings so that the app is completely closed when closing SnipAway. This way you can prevent multiple instances of the app from running when you click on the desktop/app icon. 

We hope this feedback will help you.

Your Futureglobe Support Team
