### ISSUE TITLE
Can't see any folder created in application

### ISSUE THREAD

**Issue by eserkelleci** [Futureglobe/SnipAway_IssueTracker#23]
**Describe the bug**
I installed the app recently but the folders I created cant show in the folders on sidebarö but only in settings.

**Steps to reproduce the bug**
1. Go to left sidebar
2. Click on folder icon
3. After click on 'Create Folder' button.
4. A windows appears with 'FOLDERS' section selected.
5. 'Enter a name for folder to 'Enter folder name' field.
6. Then click 'CREATE FOLDER' button.
7. Close the window and click again folder icon on left sidebar.
8. And no folder appears.

**Expected behavior**
Expecting created folders appears in left sidebar.

**Screenshots**
https://ibb.co/mCLMnVQ
https://ibb.co/3MM4vtX
https://ibb.co/wzcc544
https://ibb.co/CHqq0RL

**Desktop (please complete the following information):**
 - OS: 
Edition	Windows 10 Pro
Version	20H2
Installed on	‎05.‎07.‎2020
OS build	19042.804
Experience	Windows Feature Experience Pack 120.2212.551.0

 - Application Version [e.g. 22]
1.2.7

**Comment by Futureglobe** [comment]
Hi @eserkelleci ,

First of all sorry for the late response.
Our team is very busy right know because of the pandemic happening. 
Regarding your problem:
The folders only show up on the sidebar if you assign a snippet to that folder. Create a new snippet and click the folder icon on the top right then select the folder you want this snippet to be stored in. Now Zou will see that folder name pop up in the sidebar.

Greetings 
Your Futureglobe Support Team
